-d C:\Users\kistan\Documents\GitHub\Gowin-FPGA-Stopwatch\Stopwatch\impl\gwsynthesis\Stopwatch.vg
-p GW2AR-18C-QFN88P-8
-pn GW2AR-LV18QN88PC8/I7
-cst C:\Users\kistan\Documents\GitHub\Gowin-FPGA-Stopwatch\Stopwatch\src\StopWatchModule.cst
-cfg C:\Users\kistan\Documents\GitHub\Gowin-FPGA-Stopwatch\Stopwatch\impl\pnr\device.cfg
-sdc C:\Users\kistan\Documents\GitHub\Gowin-FPGA-Stopwatch\Stopwatch\src\Stopwatch.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
