-d C:\Users\kistan\Documents\Stopwatch\impl\gwsynthesis\Stopwatch.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst C:\Users\kistan\Documents\Stopwatch\src\StopWatchModule.cst
-cfg C:\Users\kistan\Documents\Stopwatch\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
